### ISSUE TITLE
Add abililty to manually delete containers on CodeAlly dashboard

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/CodeAlly-CodeRoad-freeCodeCamp#30]
Right now, there's no way for users to delete containers/projects. Once https://github.com/freeCodeCamp/CodeAlly-CodeRoad-freeCodeCamp/issues/11 is resolved, we hope to have users go back to the same container for a specific tutorial. The unexpected will likely happen. Having a way to delete a container in case something is broken, or someone just wants to start over would be nice.

**Comment by AdamZaczek** [comment]
This will be needed for sure. The priority seems right too - it's not needed right away but we need to have it prepared in case, an unexpected problem happens and users are locked.

**Comment by AdamZaczek** [comment]
We are halfway through adding this.

**Comment by AdamZaczek** [comment]
The proper reset project button progress was stopped due to performance tests. I added a way to delete the containers through https://app.codeally.io/app/code so you can do properly do tests @moT01.

**Comment by AdamZaczek** [comment]
We were working on the best way of handling this - a reset project button. It would delete the project and add the same one, so users that got stuck can start again.

The progress was stopped though due to performance tests. I added a way to delete the project through https://app.codeally.io/app/code so we give users a way to reset containers and so you can do properly do tests @moT01.

**Comment by moT01** [comment]
Lookin good @AdamZaczek 🎉
