### ISSUE TITLE
[deleted]

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/CodeAlly-CodeRoad-freeCodeCamp#48]
[deleted]

**Comment by AdamZaczek** [comment]
Sorry for the super late response!
I already deleted this user's account a few days ago.
User deletion is in the roadmap but we only ever had 3 requests. I will bump its priority though.

All developers log in via Github. Embeds use the same login mechanism. They just redirect to the editor app - app.codeally.

Sometimes the communication is not perfect yet which is why you had problems.
You were logged in to app.codeally only. We plan on fixing the issue you had in a week or so.

We're moving all of Codeally (including embeds!) to codeally.io pretty soon.

PS There are some other auth issues like this one [link](https://twitter.com/pacman326/status/1513392030436802565) which are caused by cache.
I think I found a consistent solution! I should be able to come back with the results after the weekend.

**Comment by AdamZaczek** [comment]
Sorry for the super late response!
I already deleted this user's account a few days ago.
User deletion is ok the roadmap but we only ever had 3 requests. I will bump its priority though.

All developers log in via Github. Embeds use the same login mechanism. They just redirect to the editor app - app.codeally.

Sometimes the communication is not perfect yet which is why you had problems.
You were logged in to app.codeally only. We plan on fixing the issue you had in a week or so.

We're moving all of Codeally (including embeds!) to codeally.io pretty soon.

PS There are some other auth issues like this one [link](https://twitter.com/pacman326/status/1513392030436802565) which are caused by the cache.
I think I found a consistent solution! I should be able to come back with the results after the weekend.

**Comment by moT01** [comment]
Adding this for reference - from one of our contributors on discord regarding GDPR compliance:

```
"explicit grant or rejection plus cookie notice with their type / usage is necessary before setting any kind of cookie.
This didn't happen when I tried to get in."
```
