### ISSUE TITLE
Files aren't getting shown/applied in workspace after being copied there

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/CodeAlly-CodeRoad-freeCodeCamp#61]
When you first open a container, CodeRoad copies the course files into the workspace (loads a commit) - but something a little goofy has started happening lately. The files seem to be getting copied, but they aren't being recognized by VSCode:

<details><summary>image</summary>

![Screen Shot 2023-06-20 at 11 24 10 AM](https://github.com/freeCodeCamp/CodeAlly-CodeRoad-freeCodeCamp/assets/20648924/5df5979a-ce4a-4c0c-9e9e-a466d0dd7a5f)

</details>

In the image above, you can see the files in the `Project` folder in the terminal, `students.sql` being one of them, but it isn't visible in the explorer on the left. Also, the settings from `.vscode/settings.json` aren't being applied. So there's no theme, the desired files aren't being hidden, and the other settings aren't applied.

If I close the container and reopen, the files are already in the workspace from when they were copied on the initial load, and everything is as it should be:

<details><summary>image</summary>

![Screen Shot 2023-06-20 at 11 31 42 AM](https://github.com/freeCodeCamp/CodeAlly-CodeRoad-freeCodeCamp/assets/20648924/3e2ab5c4-c5d5-4d18-9202-fad846a96f48)

</details>

You can still go through the courses, but it's causing a lot of confusion I think.

**Comment by AdamZaczek** [comment]
Sorry for being late to the party @moT01. I am taking a look into this.

**Comment by moT01** [comment]
Thanks @AdamZaczek 👍 Everything seems to be working real smooth again 🎉 Was there anything you did to fix this, or did it just work itself out?

**Comment by AdamZaczek** [comment]
We did a number of quality fixes to handle Linode's random VM issues. Unfortunately, I can't tell which one did the trick but we did a lot of work to make sure projects would work a lot faster and more consistently.

There's also an issue with crypto guys. Someone/some group has been creating thousands of GitHub accounts to run crypto mining operations from within CodeAlly. We've done a lot of work to stop most of this from preventing users from enjoying the courses. It's likely that the environment has been misbehaving due to the stress from these crypto miners.

**Comment by AdamZaczek** [comment]
We did a number of quality fixes to handle Linode's random VM issues. Unfortunately, I can't tell which one did the trick but we did a lot of work to make sure projects would work a lot faster and more consistently.
I want to stress that the Linode team is awesome, and we just have a very specific use-case.

There's also an issue with crypto guys. Someone/some group has been creating thousands of GitHub accounts to run crypto mining operations from within CodeAlly. We've done a lot of work to stop most of this from preventing users from enjoying the courses. It's likely that the environment has been misbehaving due to the stress from these crypto miners.

**Comment by AdamZaczek** [comment]
We did a number of quality fixes to handle Linode's random VM issues. Unfortunately, I can't tell which one did the trick but we did a lot of work to make sure projects would work a lot faster and more consistently.
I have to add that the Linode team is awesome, and we just have a very specific use-case.

There's also an issue with crypto guys. Someone/some group has been creating thousands of GitHub accounts to run crypto mining operations from within CodeAlly. We've done a lot of work to stop most of this from preventing users from enjoying the courses. It's likely that the environment has been misbehaving due to the stress from these crypto miners.

**Comment by AdamZaczek** [comment]
We did a number of quality fixes to handle Linode's random VM issues. Unfortunately, I can't tell which one did the trick but we did a lot of work to make sure projects would work a lot faster and more consistently.
I have to add that the Linode team is awesome, and we just have a very specific use-case.

There's also an issue with crypto guys. Someone/some group has been creating thousands of GitHub accounts to run crypto mining operations from within CodeAlly. We've done a lot of work to stop most of this from preventing users from enjoying the courses. It's likely that the environment has been misbehaving due to the stress from these crypto miners.

**Comment by AdamZaczek** [comment]
Thanks @moT01! We did a number of quality fixes to handle Linode's random VM issues. I can't tell which one if any did the trick but we did a lot of work to make sure projects would work a lot faster and more consistently.
I have to add that the Linode team is awesome, and we just have a very specific use-case.

There's also an issue with crypto guys. Someone/some group has been creating thousands of GitHub accounts to run crypto mining operations from within CodeAlly. We've done a lot of work to stop most of this from preventing users from enjoying the courses. It's likely that the environment has been misbehaving due to the stress from these crypto miners.

**Comment by ShaunSHamilton** [comment]
@AdamZaczek 

> There's also an issue with crypto guys. Someone/some group has been creating thousands of GitHub accounts to run crypto mining operations from within CodeAlly.

Do you know if this is coming from our domain? Or, is it just another of CodeAlly -used domains?

Reason I ask: Is there anything you know of we can do to mitigate this?

**Comment by AdamZaczek** [comment]
Thank you @ShaunSHamilton.
Previously, attacks came through CodeAlly directly and not Freecodecamp. I will let you know if we notice the malicious traffic coming from Freecodecamp.

The biggest problem with mitigation is, the crypto miners are adjusting the attack patterns, but we can adjust too ;)
The situation seems way more stable now, as we made it non-rewarding and tough to game the system along with making previous patterns obsolete.

**Comment by moT01** [comment]
Closing this since it's no longer an issue. Let us know if there's ever anything we can do to help @AdamZaczek 👍
